import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TireHeader from "@/components/header";
import TireFooter from "@/components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Tire of Crestmont</title>
      </head>
      <body className={inter.className}>
        <main>
          <TireHeader />
          <div className="flex items-center justify-center">{children}</div>
          <TireFooter />
        </main>
      </body>
    </html>
  );
}
