import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TireHeader from "@/components/header";
import FooterWithSocialLinks from "@/components/footer";
import "./globals.css";
import { ThemeProvider } from "@material-tailwind/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            <TireHeader />
            <div className="flex items-center justify-center w-full">
            {children}
            </div>
            <FooterWithSocialLinks />
          </main>
      </body>
    </html>
  );
}
