-- This file is used to initialize the tables for the project Tire


-----------------------------------Part 1 : User&Role-------------------------------------

-- roles of users
DROP TABLE IF EXISTS u_roles;
CREATE TABLE u_roles (
    id CHAR(4) PRIMARY KEY,
    -- role id, xxxx 
    -- xxxx = ROOT : super admin,  ADMN : administrator, MANR : store's manager , STAF : store's staff, CUST : customer
    session_ttl INTEGER,
    -- how long user can live after logining in, unit is hour
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- users
DROP TABLE IF EXISTS u_users;
CREATE TABLE u_users (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    user_name VARCHAR(100) NOT NULL,
    -- user name 
    nick_name VARCHAR(100) NOT NULL,
    -- nick name 
    role_id CHAR(4),
    -- role id
    address VARCHAR(200),
    -- address, including street, zip code
    phone_number VARCHAR(20) UNIQUE,
    -- phone number (can be used to login)
    email VARCHAR(100) UNIQUE,
    -- email (can be used to login)
    photo_url VARCHAR(200),
    -- photo url
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- login authentication of users
-- login session will be stored in the client (cookie or local storage)
DROP TABLE IF EXISTS u_auths;
CREATE TABLE u_auths (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    user_id CHAR(21),
    -- the user who logined in 
    login_name VARCHAR(100) UNIQUE,
    -- login name (can be used to login)
    auth_pass VARCHAR(512),
    -- md5 string of readable password
    session_ttl INTEGER,
    -- how long user can live after logining in, unit is hour
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- login sessions by JWT
DROP TABLE IF EXISTS u_login_sessions;
CREATE TABLE u_login_sessions (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    -- this field would be written into JWT token, which are used to control the validation of tickets
    user_id CHAR(21),
    -- the user who have logined in 
    user_agent VARCHAR(256),
    -- User-Agent from the brower, which would be used to anylyse customers
    exp_at TIMESTAMP NOT NULL,
    -- time of expiration (using the time of server)
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);


-----------------------------------Part 2 : Product-------------------------------------


-- installers (because the platform contains many installers)
DROP TABLE IF EXISTS installers;
CREATE TABLE installers (
    id CHAR(10) PRIMARY KEY,
    -- id, format : zzssccbbbb
    -- zz : zip code of the nation , ref : https://en.wikipedia.org/wiki/List_of_postal_codes, such as Canada is 'CA'
    -- ss : code of the states/provinces in the nation, decided by us
    -- cc : code of the cities in the states/provinces, decided by us
    -- bbbb : the code of the installer
    installer_name VARCHAR(100),
    -- installer name
    introduction VARCHAR(500),
    -- introduction
    website_url VARCHAR(200),
    -- website of the installer
    owner CHAR(21),
    -- user id of the store's owner
    address VARCHAR(200),
    -- address, including street, zip code and geographical coordinates etc
    phone_number VARCHAR(20),
    -- phone number
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- workshops of installers
DROP TABLE IF EXISTS installer_workshops;
CREATE TABLE installer_workshops (
    id CHAR(14) PRIMARY KEY,
    -- id, format : zzssccbbbbdddd
    -- zz : zip code of the nation , ref : https://en.wikipedia.org/wiki/List_of_postal_codes, such as Canada is 'CA'
    -- ss : code of the states/provinces in the nation, decided by us
    -- cc : code of the cities in the states/provinces, decided by us
    -- bbbb : the code of the installer
    -- dddd : the sequence number of the workshop owned by the installer
    workshop_name VARCHAR(100),
    -- workshop name
    introduction VARCHAR(200) DEFAULT '',
    -- introduction
    manager CHAR(21),
    -- manager id of the workshop
    address VARCHAR(200) DEFAULT '',
    -- address, including street, zip code and geographical coordinates etc
    phone_number VARCHAR(20) DEFAULT '',
    -- phone number
    latitude NUMERIC(10, 6),
    -- latitude (google)
    longitude NUMERIC(10, 6),
    -- longtitude (google)
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- categories of all products
DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
    id CHAR(3) PRIMARY KEY,
    -- id, format : xdd
    -- x rules :  1 : tire&wheel | 2 : accessories
    title VARCHAR(50),
    -- title
    introduction VARCHAR(200) DEFAULT '',
    -- introduction
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- brands of products (including tires)
DROP TABLE IF EXISTS brands;
CREATE TABLE brands (
    id CHAR(4) PRIMARY KEY,
    -- id, format : xddd
    -- xx rules :  1 : Premium | 2 : Mid-range | 3,4,5 : Economy | 6,7,8,9 : Budget
    brand VARCHAR(50) NOT NULL,
    -- name of maker, such as Michelin
    grade CHAR(1) DEFAULT '1',
    -- 1: Premium, 2: Mid-range, 3: Economy, 6: Budget
    owner VARCHAR(100) DEFAULT '',
    -- the company that owns the brand
    introduction VARCHAR(200) DEFAULT '',
    -- introduction of the brand
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- providers of products
DROP TABLE IF EXISTS providers;
CREATE TABLE providers (
    id CHAR(4) PRIMARY KEY,
    -- id, format : xddd, range = [1000,9999]
    -- x : 1 : manufactuer,  2 : First-class dealer,  3,4 : Second-class dealer, 5,6,7,8,9: Third-class dealer
    title VARCHAR(50) NOT NULL,
    -- title
    introduction VARCHAR(200) DEFAULT '',
    -- introduction
    class CHAR(1) DEFAULT '1',
    -- provider's class 
    -- 1 : manufactuer,  2 : First-class dealer,  3,4 : Second-class dealer, 5,6,7,8,9: Third-class dealer
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- SPU defines of products
DROP TABLE IF EXISTS products;
CREATE TABLE products (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    spu_name VARCHAR(100),
    -- spu name
    description VARCHAR(200) DEFAULT '',
    -- introduction
    category_id CHAR(3),
    -- category id
    brand_id CHAR(4),
    -- brand id
    model VARCHAR(50),
    -- model name
    product_code VARCHAR(100),
    -- ccc-bbbb-pppp-model
    -- ccc : category id, bbbb : brand id, pppp : provider id, model : model name (only includes [a-zA-Z0-9_])
    status CHAR(1) DEFAULT '0',
    -- 0 : not available , 1 : available
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- attributes of SPU
-- using horizontal fields table to improve the performance of searching
DROP TABLE IF EXISTS product_attrs;
CREATE TABLE product_attrs (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    product_id CHAR(21),
    -- product id (foreign key)
    attr_01 VARCHAR(30),
    attr_02 VARCHAR(30),
    attr_03 VARCHAR(30),
    attr_04 VARCHAR(30),
    attr_05 VARCHAR(30),
    attr_06 VARCHAR(30),
    attr_07 VARCHAR(30),
    attr_08 VARCHAR(30),
    attr_09 VARCHAR(30),
    attr_10 VARCHAR(30),
    attr_11 VARCHAR(30),
    attr_12 VARCHAR(30),
    attr_13 VARCHAR(30),
    attr_14 VARCHAR(30),
    attr_15 VARCHAR(30),
    attr_16 VARCHAR(30),
    attr_17 VARCHAR(30),
    attr_18 VARCHAR(30),
    attr_19 VARCHAR(30),
    attr_20 VARCHAR(30),
    -- attr fields, 01-20th's max length is 30
    attr_21 VARCHAR(100),
    attr_22 VARCHAR(100),
    attr_23 VARCHAR(100),
    attr_24 VARCHAR(100),
    attr_25 VARCHAR(100),
    attr_26 VARCHAR(100),
    attr_27 VARCHAR(100),
    attr_28 VARCHAR(100),
    attr_29 VARCHAR(100),
    attr_30 VARCHAR(100),
    -- attr fields, 21-30th's max length is 100
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);


-----------------------------------Part 3 : Inventory-------------------------------------


-- SKU defines of products
-- ref : https://en.wikipedia.org/wiki/Stock_keeping_unit)
DROP TABLE IF EXISTS product_skus;
CREATE TABLE product_skus (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    product_id CHAR(21),
    -- product id (foreign key)
    store_id CHAR(10),
    -- store id (NOTE : sku data owned by the store)
    title VARCHAR(100),
    -- title
    subtitle VARCHAR(100),
    -- subtitle
    description VARCHAR(200) DEFAULT '',
    -- description
    old_unit_price NUMERIC(8, 2),
    -- old price
    unit_price NUMERIC(8, 2),
    -- price
    stock_amount INTEGER,
    -- the amount in the stock
    update_version INTEGER,
    -- increase 'update_version' value when update 'stock_amount'
    status CHAR(1) DEFAULT '0',
    -- 0 : not available , 1 : available
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- attributes of SKU
-- using horizontal fields table to improve the performance of searching
DROP TABLE IF EXISTS product_sku_attrs;
CREATE TABLE product_sku_attrs (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    product_sku_id CHAR(21),
    -- product sku id (foreign key)
    attr_01 VARCHAR(30),
    attr_02 VARCHAR(30),
    attr_03 VARCHAR(30),
    attr_04 VARCHAR(30),
    attr_05 VARCHAR(30),
    attr_06 VARCHAR(30),
    attr_07 VARCHAR(30),
    attr_08 VARCHAR(30),
    attr_09 VARCHAR(30),
    attr_10 VARCHAR(30),
    -- attr fields, 01-10th's max length is 30
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);


-- the stock change flow records of orders
-- create it after making order
DROP TABLE IF EXISTS stock_order_flows;
CREATE TABLE stock_order_flows (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    order_id CHAR(21),
    -- order id
    product_sku_id CHAR(21),
    -- product sku id 
    shopping_item_id CHAR(21),
    -- shopping item id 
    buy_amount INTEGER,
    -- the amount of buying
    exp_at TIMESTAMP,
    -- the time of expiration, normarl is 30 mins
    -- if expire, need to put the stock back
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

DROP INDEX IF EXISTS UNIQUE_STOCK_ORDER_FLOW;
CREATE UNIQUE INDEX UNIQUE_STOCK_ORDER_FLOW 
    ON stock_order_flows (product_sku_id, order_id);

-- the stock change flow records of refunded orders
-- create it after making refund
DROP TABLE IF EXISTS stock_refund_flows;
CREATE TABLE stock_refund_flows (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    refund_id CHAR(21),
    -- refund id
    order_id CHAR(21),
    -- order id
    product_sku_id CHAR(21),
    -- product sku id 
    shopping_item_id CHAR(21),
    -- shopping item id 
    refund_amount INTEGER,
    -- the amount of refund
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);


-----------------------------------Part 3 : Restock-------------------------------------

-- the records of loading stock
DROP TABLE IF EXISTS stock_loads;
CREATE TABLE stock_loads (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    product_id CHAR(21),
    -- product id (foreign key)
    product_sku_id CHAR(21),
    -- product sku id (foreign key)
    provider_id CHAR(4),
    -- provider id
    store_id CHAR(10),
    -- store id (NOTE : sku data owned by the store)
    loaded_amount INTEGER,
    -- the amount of loading
    unit_price NUMERIC(8, 2),
    -- price
    operator CHAR(21),
    -- user id of operator (staff or manager)
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);


-----------------------------------Part 4 : Sales&Marketing-------------------------------------

-- coupons
DROP TABLE IF EXISTS coupons;
CREATE TABLE coupons (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    type CHAR(1),
    -- type of coupon
    -- C : equals cash ,  D : discount 
    title VARCHAR(100),
    -- title of the coupon
    introduction VARCHAR(100),
    -- introduction of the coupon
    strategy VARCHAR(30),
    -- strategy of applying coupon, which decide what the codes should do
    init_parameters JSONB,
    -- the inited parameters of the coupon
    coupon_amount INTEGER DEFAULT -1,
    -- the amount of coupons, -1 means unlimited
    update_version INTEGER,
    -- increase 'update_version' value when update 'coupon_amount'
    exp_at TIMESTAMP,
    -- the time of expiration
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- coupons of customers
DROP TABLE IF EXISTS customer_coupons;
CREATE TABLE customer_coupons (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    customer_id CHAR(21),
    -- customer id (foreign key)
    type CHAR(1),
    -- type of coupon
    -- C : cash ,  D : discount 
    title VARCHAR(100),
    -- title of the coupon
    introduction VARCHAR(500),
    -- introduction of the coupon
    strategy VARCHAR(30),
    -- strategy of applying coupon, which decide what the codes should do
    init_parameters JSONB,
    -- the inited parameters of the coupon
    exp_at TIMESTAMP,
    -- the time of expiration
    order_id CHAR(21) DEFAULT '',
    -- order id, '' means this coupon is not under an order
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- reviews of customers
DROP TABLE IF EXISTS customer_reviews;
CREATE TABLE customer_reviews (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    customer_id CHAR(21),
    -- customer id (foreign key)
    order_id CHAR(21),
    -- order id which customer paid
    product_sku_id CHAR(21),
    -- product sku id which customer bought
    review_content VARCHAR(500),
    -- review content
    rating INTEGER,
    -- customer give the order a rating score, range = [1,2,3,4,5], 5 is the best
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);



-----------------------------------Part 5 : Shopping Cart&Order-------------------------------------


-- shopping cart
-- shopping items of customer
-- NOTE : when customer put items into his shopping cart, we would automatically merge ordere shopping items (order_id=='') by sku 
DROP TABLE IF EXISTS shopping_items;
CREATE TABLE shopping_items (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    customer_id CHAR(21),
    -- customer id (foreign key)
    product_sku_id CHAR(21),
    -- product sku id (foreign key)
    shopping_amount INTEGER,
    -- the amount of buying
    order_id CHAR(21) DEFAULT '',
    -- order id, '' means this item is not under an order
    status VARCHAR(20),
    -- status of item,
    -- NEED_PAID : to be paid
    -- CANCELLED : cancelled
    -- FULLY_PAID : paid for all goods
    -- DELIVERED : have been delivered
    -- REFUND : need to refund
    -- WAIT_DELIVERY : wait for the delivery
    -- COMPLETED : order is completed
    -- CLOSED : closed by the staff (REFUND -> CLOSED)
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- orders
DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    customer_id CHAR(21),
    -- customer id (foreign key)
    nick_name VARCHAR(100) NOT NULL,
    -- nick name 
    delivery_address VARCHAR(200),
    -- address, including street, zip code
    phone_number VARCHAR(20),
    -- phone number 
    email VARCHAR(100),
    -- email 
    installer_workshop_id CHAR(14),
    -- installer's workshop which was choosen by customer
    pickup_address VARCHAR(200),
    -- pickup address
    shipping_method VARCHAR(20),
    -- shipping method : PICKUP | DELIVERY | NONE
    items_price NUMERIC(8, 2),
    -- total price for items
    gst_fee NUMERIC(8, 2),
    -- the fee for tax GST, Goods and Services Tax
    pst_fee NUMERIC(8, 2),
    -- the fee for tax PST, Provincial Tax
    hst_fee NUMERIC(8, 2),
    -- the fee for tax HST, Harmonized Sales Tax
    delivery_fee NUMERIC(8, 2),
    -- the fee for delivery
    discounted_price NUMERIC(8, 2),
    -- the money which need to be removed from the total price
    actual_price NUMERIC(8, 2),
    -- actual price (after applying coupons)
    status VARCHAR(20),
    -- status 
    -- NEED_PAID : to be paid
    -- CANCELLED : cancelled
    -- FULLY_PAID : paid for all goods
    -- DELIVERED : have been delivered
    -- REFUND : need to refund
    -- WAIT_DELIVERY : wait for the delivery
    -- COMPLETED : order is completed
    -- CLOSED : closed by the staff (REFUND -> CLOSED)
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);

-- orders
DROP TABLE IF EXISTS refund_orders;
CREATE TABLE refund_orders (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    customer_id CHAR(21),
    -- customer id (foreign key)
    order_id CHAR(21),
    -- order id which need refund (maybe partially refund)
    updated_items_price NUMERIC(8, 2),
    -- total price for items (updated)
    updated_gst_fee NUMERIC(8, 2),
    -- the fee for tax GST, Goods and Services Tax (updated)
    updated_pst_fee NUMERIC(8, 2),
    -- the fee for tax PST, Provincial Tax (updated)
    updated_hst_fee NUMERIC(8, 2),
    -- the fee for tax HST, Harmonized Sales Tax (updated)
    charge_delivery_fee NUMERIC(8, 2),
    -- the fee for delivery 
    -- (if the customer get free-delivery service but he refund all goods, so he have to pay us the delivery fee)
    discounted_price NUMERIC(8, 2),
    -- the money which need to be removed from the total price
    updated_actual_price NUMERIC(8, 2),
    -- actual price (after applying coupons) (updated)
    refunded_money NUMERIC(8, 2),
    -- the money which should refund to customer
    -- if the value is negtive, customer need charge some money
    status VARCHAR(20),
    -- status 
    -- NEED_PAID : to be paid
    -- CANCELLED : cancelled
    -- FULLY_PAID : paid for all goods
    -- REFUND : need to refund
    -- WAIT_DELIVERY : wait for the delivery
    -- COMPLETED : order is completed
    -- CLOSED : closed by the staff (REFUND -> CLOSED)
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);


-----------------------------------Part 6 : Payment-------------------------------------

-- payments
DROP TABLE IF EXISTS payments;
CREATE TABLE payments (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    order_id CHAR(21),
    -- order id
    paid_money NUMERIC(8, 2),
    -- the money paid
    payment_way VARCHAR(50),
    -- the way of payment
    -- CREDIT, DEBIT, PAYPAL, APPALPAY, ALIPAY
    status VARCHAR(20),
    -- status : SUCCESS | FAILED
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);


-----------------------------------Part 7 : Installation&Tracking-------------------------------------

-- appointment of installation
DROP TABLE IF EXISTS appointments;
CREATE TABLE appointments (
    id CHAR(21) PRIMARY KEY,
    -- id, generated by nanoid
    customer_id CHAR(21),
    -- customer id (foreign key)
    order_id CHAR(21),
    -- order id
    workshop_address VARCHAR(200),
    -- the address of workshop which will help customer
    appointment_time TIMESTAMP,
    -- the time of appointment
    processor CHAR(21),
    -- the staff who handle the installation
    status VARCHAR(20),
    -- status : ACCEPED | PENDING | FINISHED
    invalid BOOLEAN default FALSE,
    -- invalid = true, means data is invalid
    c_at TIMESTAMP DEFAULT now(),
    u_at TIMESTAMP DEFAULT now()
);


